"""
The ingest payload shared by the agent (producer) and the server (consumer).

Only the fields the service needs are here. Health, stamina, hunger and thirst are available from RCON but are
dropped in the agent and have no place in this schema, so they can never reach the backend.
"""

from datetime import datetime
from typing import Annotated, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, StringConstraints, field_validator

SCHEMA_VERSION: Literal[1] = 1

MAX_PLAYERS_PER_SNAPSHOT = 500
MAX_SNAPSHOTS_PER_BATCH = 2000

# Steam64 ids are 17 digits, EOS product user ids are 32 hex characters. Anything id-shaped is accepted and
# treated as opaque.
PlayerId = Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9_-]{1,64}$")]
DinoClass = Annotated[str, StringConstraints(pattern=r"^[A-Za-z0-9_]{1,64}$")]
# World coordinates in Unreal units (cm). The bound only rejects garbage; real maps are far smaller.
Coordinate = Annotated[float, Field(allow_inf_nan=False, ge=-1e8, le=1e8)]


class PlayerSample(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    player_id: PlayerId
    player_name: Annotated[str, StringConstraints(max_length=128)]
    dino_class: DinoClass | None = None
    growth: Annotated[float, Field(ge=0.0, le=1.0, allow_inf_nan=False)] | None = None
    x: Coordinate
    y: Coordinate
    z: Coordinate


class Snapshot(BaseModel):
    """Every player on one server at one moment, from a single RCON response."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    # Generated by the agent at poll time; the server deduplicates on it, so retries are idempotent however the
    # agent regroups snapshots into batches.
    snapshot_id: UUID
    captured_at: AwareDatetime
    players: Annotated[list[PlayerSample], Field(max_length=MAX_PLAYERS_PER_SNAPSHOT)]

    @field_validator("players")
    @classmethod
    def _unique_players(cls, players: list[PlayerSample]) -> list[PlayerSample]:
        ids = [p.player_id for p in players]
        if len(ids) != len(set(ids)):
            raise ValueError("duplicate player_id in snapshot")
        return players


class IngestBatch(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    schema_version: Literal[1] = SCHEMA_VERSION
    agent_version: Annotated[str, StringConstraints(max_length=32)]
    snapshots: Annotated[list[Snapshot], Field(min_length=1, max_length=MAX_SNAPSHOTS_PER_BATCH)]


class IngestResponse(BaseModel):
    accepted_snapshots: int
    duplicate_snapshots: int
    rejected_snapshots: int
    rows: int
    received_at: datetime
